<%-- SPWidgetsDemos --%>
<%-- Generated by yeoman sharepoint-spa --%>
<%@ Page language="C#" MasterPageFile="~masterurl/default.master"
        Inherits="Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=12.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %>
<%@ Register
        Tagprefix="SharePoint"
        Namespace="Microsoft.SharePoint.WebControls"
        Assembly="Microsoft.SharePoint, Version=12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<%@ Register
        Tagprefix="Utilities"
        Namespace="Microsoft.SharePoint.Utilities"
        Assembly="Microsoft.SharePoint, Version=12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<%@ Import Namespace="Microsoft.SharePoint" %>
<%@ Register
        Tagprefix="WebPartPages"
        Namespace="Microsoft.SharePoint.WebPartPages"
        Assembly="Microsoft.SharePoint, Version=12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<asp:Content ContentPlaceHolderId="PlaceHolderPageTitle" runat="server">SPWidgetsDemos</asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderPageTitleInTitleArea" runat="server">SPWidgetsDemos</asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderAdditionalPageHead" runat="server">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SPWidgetsDemos</title>
    <meta name="description" content="SPWidgetsDemos App">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--[if lt IE 10]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/Base64/0.3.0/base64.min.js"></script>
        <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.13/es5-shim.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.13/es5-sham.min.js"></script>
    <![endif]-->


    <style type="text/css">
        #s4-leftpanel,
        #sideNavBox {
            display:none !important;
        }
        .s4-ca,
        #contentBox {
            margin-left: .5em !important;
            width: 98%;
        }
    </style>

    <link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/2.2.0/fabric.min.css">
    <link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/2.2.0/fabric.components.min.css">

</asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderSearchArea" runat="server">
    <SharePoint:DelegateControl runat="server" ControlId="SmallSearchInputBox" />
</asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderLeftActions" runat="server"></asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderPageDescription" runat="server"></asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderBodyRightMargin" runat="server"></asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderPageImage" runat="server"></asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderLeftNavBar" runat="server"></asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderNavSpacer" runat="server"></asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderMain" runat="server">
<div id="spwidgets_dev">
    <div>
        <select id="demo_selector">
            <option value="">Select...</option>
            <option value="SPPeoplePicker">SPPeoplePicker</option>
        </select>
    </div>
    <div id="spwidgets_dev_demo"></div>
    <div style="margin-top: 5em;border-top:1px solid lightgrey;padding:1em;">@BUILD | @DATE</div>
</div>
<script type="text/javascript" src="../vendor/requirejs/require.js"></script>
<script>
(function(){
    var require = requirejs.config({
            baseUrl: "../",
            urlArgs: '@BUILD',
            paths: {
                less:                   'vendor/require-less/less',
                lessc:                  'vendor/require-less/lessc',
                normalize:              'vendor/require-less/normalize',
                text:                   'vendor/requirejs-text/text',
                'vendor/jsutils':       'vendor/common-micro-libs/src/jsutils',
                'vendor/domutils':      'vendor/common-micro-libs/src/domutils'
            },
            less: {
                relativeUrls: true
            }
        });

    require([
        'dev/src/SPPeoplePickerDemo/SPPeoplePickerDemo'
    ], function(
        SPPeoplePickerDemo
    ){
        var demoCntr = document.querySelector("#spwidgets_dev_demo"),
            demoSelector = document.querySelector("#demo_selector"),
            currentDemo;

        demoSelector.addEventListener("change", function(){
            if (currentDemo) {
                currentDemo.destroy();
            }

            switch (demoSelector.value) {
                case "SPPeoplePicker":
                    currentDemo = SPPeoplePickerDemo.create();
                    currentDemo.appendTo(demoCntr);
                    break;
            }

        });
    });

}());

</script>

</asp:Content>
